### ISSUE TITLE
What about multiple tests?

### ISSUE THREAD

**Issue by tunnckoCore** [jstransformers/test-jstransformer#11]
Multiple test cases and etc? That's why im against that philosophy "tests are just to prove code is working" - No, tests are for 2 things.. 200% coverage, cuz 100% isn't enough sometimes to prove code is working as you expect; and examples and use cases, cuz docs and readmes not enough. Cuz in readme should have only the simplest and shortest working use case.

I always look the tests of every package in daily basis and find more and more use cases. And always look them, cuz readmes and docs are not enough in 99% of the time.

And hence.. that boilerplate merging puked on every transformer history, imo. Sorry for the tone, but im horrified. Other than that @RobLoach did awesome work around these months.

**Comment by RobLoach** [comment]
Adding more tests are always a good idea. Could result in showing some false-positives too.

> And hence.. that boilerplate merging puked on every transformer history, imo. Sorry for the tone, but im horrified.

Feel free to discuss over at https://github.com/jstransformers/boilerplate/issues/27 .

**Comment by RobLoach** [comment]
As a side note to adding two tests that test the same thing...

> Insanity is doing the same thing over and over again and expecting different results -- Einstein

I'm all for more tests, as long as they improve use case coverage, without adding more maintenance on our side.

**Comment by tunnckoCore** [comment]
> without adding more maintenance on our side.

i cant realize what is the "more maintenance" point, when you just set them one time and then they are just plus when adding/fixing more bugs. they're never minus.

but nevermind

> I'm all for more tests, as long as they improve use case coverage

minimum

**Comment by tunnckoCore** [comment]
as you can see, i always write as much tests as possible, no matter coverage is 100% or 101%, and as you can see i have so much repos and libs that i didn't update soon. i mean.. they never made me problems. when im not sure for something and i think "damn i should fix that" i just see that it is handled in the tests, so no update and "more maintenance" is needed.

before i release v1, i write every thing as it is for last time, with maximum quality and coverage as im possible at that moment. i never write it thinking "i'll back later, it can stay buggy for now, it can stay 0.1.0-1.32.432.4234234-pre-pre".

**Comment by TimothyGu** [comment]
Guys, calm down. I believe that there _should_ be a way to write multiple tests, simply for that feature's sake, but we shouldn't coerce everyone to write multiple tests that test the the same thing. If there's a bug, fix it and write a test for it. If there isn't, don't waste time testing the same thing over and over again just to reach "200%."

**Comment by tunnckoCore** [comment]
> Guys, calm down.

I am down.

> don't waste time testing the same thing over and over again just to reach "200%."

Are you thinking guys, that I'm staying 5 days on some module before release it to "invent some use cases and test them"? - No, I just write what is in my mind in the moment of writing the module.

I'm not forcing you to write tests for 200%, everyone have head and way to do the things. Just don't force me to write only one shitty test case (current implementation of this package), or in future only for 100% (cuz currently it's impossible).

**Comment by RobLoach** [comment]
Tim has added a  bunch of tests in https://github.com/jstransformers/jstransformer/pulls . 900% code coverage!

**Comment by tunnckoCore** [comment]
as here https://github.com/tunnckoCore/benz and https://github.com/tunnckoCore/benz/issues/4

100% never means "enough", that's why i said and think in "200%"
