### ISSUE TITLE
Code style standard

### ISSUE THREAD

**Issue by RobLoach** [jstransformers/test-jstransformer#15]
RE: https://github.com/jstransformers/jstransformer/issues/89

**Comment by RobLoach** [comment]
https://www.npmjs.com/package/semistandard

**Comment by RobLoach** [comment]
http://npm.im/xo

**Comment by ForbesLindesay** [comment]
Every time I read through one of these I see a load of things where they're being too restrictive, or (in the case of standard/semistandard) just completely ignoring how most developers write JavaScript and going their own way.
- standard: the rest of the world uses semicolons
- semistandard: the rest of the world doesn't put a space after function names
- xo: blocks use of `new Function` which we're going to need in a few jstransformers

I think the best bet would be to add our own eslint config to this project and add a new command `test-jstransformer lint` that lints according to that config.

**Comment by calebeby** [comment]
We are now using xo (jstransformers/boilerplate#37). Regarding `new Function`, we can just add in the line before:
```js
// eslint-disable-next-line no-new-func
```
That way we have to be aware when we are doing it, but we still can get the linter to pass.
