### ISSUE TITLE
Does not recognize newlines when comparing text

### ISSUE THREAD

**Issue by MylesBorins** [jstransformers/test-jstransformer#25]
an input

```

test

```

will get a false positive testing against the expected output of

```
test
```

**Comment by RobLoach** [comment]
This is by design. The string is trimmed before the assertion takes place.

**Comment by MylesBorins** [comment]
Fair enough. This allows for regressions in transformers who have newlines in expected output.

Closing, but skeptical

**Comment by RobLoach** [comment]
Restoredededed it.
